# substitutions:
#   device_description: ${name} gemaakt door huizebruin.nl versie ${vdate} .
#   name: s0tool-standard

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"
  
dashboard_import:
  package_import_url: github://huizebruin/testen/pulscounter.yaml

packages:   
  remote_package:
    url: https://github.com/huizebruin/testen/
    ref: main
    files: 
      - components/basis.yaml
      - components/2000imp.yml
      - components/watermeter.yaml            
    refresh: 0d 
